package shared.presentation.panels;

import shared.application.configuration.ApplicationConfiguration;
import shared.application.configuration.ConfigurationVariable;
import shared.presentation.localization.Localization;
import shared.presentation.localization.LocalizationKey;

/**
 * Panel which shows information about the application.
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Constructor.
     */
    public AboutPanel() {
        initComponents();

        this.setProgramName();
        this.setVersion();
        this.setProjectDetails();
    }

    /**
     * Set the program name to the panel.
     */
    private void setProgramName() {
        String programNameText = Localization.getLocalization(LocalizationKey.PROGRAM_NAME);
        String applicationName = "FGEN";
        this.programName.setText(String.format("%s: %s", programNameText, applicationName));
    }

    /**
     * Set the version to the panel.
     */
    private void setVersion() {
        String versionText = Localization.getLocalization(LocalizationKey.VERSION);
        String applicationVersion = ApplicationConfiguration.getConfigurationVariable(ConfigurationVariable.VERSION);
        this.version.setText(String.format("%s: %s", versionText, applicationVersion));
    }

    /**
     * Set the project details to the panel.
     */
    private void setProjectDetails() {
        String projectDetailsText = Localization.getLocalization(LocalizationKey.PROJECT_DETAILS);
        String projectUrl = ApplicationConfiguration.getConfigurationVariable(ConfigurationVariable.PROJECT_URL);
        this.projectDetails.setText(String.format("%s: %s", projectDetailsText, projectUrl));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programName = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        projectDetails = new javax.swing.JLabel();

        programName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programName.setText("${PROGRAM_NAME}: ${NAME}");

        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("${VERSION}: ${VERSION_NUMBER}");

        projectDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectDetails.setText("${PROJECT_DETAILS}: ${PROJECT_URL}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(programName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(programName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(projectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel programName;
    private javax.swing.JLabel projectDetails;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
