package template.presentation.panels;

import java.awt.GridLayout;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import shared.persistence.exceptions.NotDefinedDatabaseContextException;
import shared.presentation.localization.Localization;
import shared.presentation.localization.LocalizationKey;
import template.application.Template;
import template.application.usecases.ShowTemplate;
import template.persistence.mongo.MongoTemplateRepository;

/**
 * Panel which shows the template details.
 */
public class ShowTemplatePanel extends javax.swing.JPanel {

    /**
     * Template fields panel.
     */
    private TemplateFieldsPanel templateFieldsPanel;

    /**
     * Constructor.
     *
     * @param code The code of the template to show the data.
     */
    public ShowTemplatePanel(int code) {
        initComponents();
        initializeLabels();
        initializeInputs(code);
    }

    /**
     * Initialize the form labels.
     */
    private void initializeLabels() {
        String codeLabelText = Localization.getLocalization(LocalizationKey.CODE);
        String codeLabelFormattedText = String.format("%s:", codeLabelText);
        this.codeLabel.setText(codeLabelFormattedText);

        String nameLabelText = Localization.getLocalization(LocalizationKey.NAME);
        String nameLabelFormattedText = String.format("%s:", nameLabelText);
        this.nameLabel.setText(nameLabelFormattedText);

        String fileLabelText = Localization.getLocalization(LocalizationKey.FILE);
        String fileLabelFormattedText = String.format("%s:", fileLabelText);
        this.fileLabel.setText(fileLabelFormattedText);

        String isDeletedLabelText = Localization.getLocalization(LocalizationKey.IS_DELETED);
        String isDeletedFormattedText = String.format("%s:", isDeletedLabelText);
        this.isDeletedLabel.setText(isDeletedFormattedText);
    }

    /**
     * Initialize the form inputs.
     */
    private void initializeInputs(int templateCode) {
        Template template = this.showTemplate(templateCode);

        Map<String, String> templateFields = new HashMap<>();

        if (template != null) {
            this.codeInput.setText(Integer.toString(templateCode));
            this.nameInput.setText(template.getName());
            this.isDeletedCheckbox.setSelected(template.isDeleted());

            // File extension.
            File file = template.getFile();
            String fileName = file.getName();
            int lastPointIndex = fileName.lastIndexOf(".");
            String fileExtension = fileName.substring(lastPointIndex);

            String fileLabelText = String.format("Template%d%s", templateCode, fileExtension);
            this.fileInput.setText(fileLabelText);

            // Template fields.
            templateFields = template.getFields();
        }

        this.templateFieldsPanel = new TemplateFieldsPanel(templateFields);
        this.bookedPanel.setLayout(new GridLayout());
        this.bookedPanel.add(templateFieldsPanel);
    }

    /**
     * Execute the show template use case.
     *
     * @param code The code of the template to show.
     */
    private Template showTemplate(int code) {
        try {
            MongoTemplateRepository templateRepository = new MongoTemplateRepository();
            ShowTemplate showTemplate = new ShowTemplate(templateRepository);
            return showTemplate.execute(code);
        } catch (NotDefinedDatabaseContextException ex) {
            String className = ShowTemplatePanel.class.getName();
            Logger.getLogger(className).log(Level.INFO, "Template not shown because the database has not been found", ex);
        }

        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookedPanel = new javax.swing.JPanel();
        codeLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();
        codeInput = new javax.swing.JLabel();
        isDeletedLabel = new javax.swing.JLabel();
        isDeletedCheckbox = new javax.swing.JCheckBox();
        nameLabel = new javax.swing.JLabel();
        fileInput = new javax.swing.JLabel();

        bookedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout bookedPanelLayout = new javax.swing.GroupLayout(bookedPanel);
        bookedPanel.setLayout(bookedPanelLayout);
        bookedPanelLayout.setHorizontalGroup(
            bookedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bookedPanelLayout.setVerticalGroup(
            bookedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        codeLabel.setText("${CODE}:");

        nameInput.setEditable(false);

        fileLabel.setText("${FILE}:");

        codeInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        isDeletedLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isDeletedLabel.setText("${IS_DELETED}:");

        isDeletedCheckbox.setEnabled(false);

        nameLabel.setText("${NAME}:");

        fileInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileLabel)
                            .addComponent(nameLabel)
                            .addComponent(codeLabel))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(isDeletedLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codeInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameInput)
                            .addComponent(fileInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(isDeletedCheckbox)
                        .addContainerGap(281, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fileLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(fileInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isDeletedLabel)
                    .addComponent(isDeletedCheckbox))
                .addGap(18, 18, 18)
                .addComponent(bookedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookedPanel;
    private javax.swing.JLabel codeInput;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel fileInput;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JCheckBox isDeletedCheckbox;
    private javax.swing.JLabel isDeletedLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
