package shared.presentation;

import java.awt.Container;
import javax.swing.JPanel;
import shared.presentation.localization.Localization;
import shared.presentation.localization.LocalizationKey;
import shared.presentation.panels.AboutPanel;

/**
 * Main application frame.
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Constructor.
     */
    public MainFrame() {
        initComponents();

        this.redirectToAbout();
    }

    /**
     * Set the main frame title.
     *
     * Keep in mind that the application name will be always added at the end of
     * the title separated by a hyphen.
     *
     * @param title The title to set.
     */
    @Override
    public void setTitle(String title) {
        String frameTitle = String.format("%s - FGEN", title);
        super.setTitle(frameTitle);
    }

    /**
     * Open the given panel.
     *
     * @param panel The panel to open.
     */
    private void openPanel(JPanel panel) {
        Container layoutContainer = this.getContentPane();
        layoutContainer.removeAll();
        layoutContainer.add(panel);
        layoutContainer.repaint();
        layoutContainer.revalidate();
    }

    /**
     * Redirect to the given panel.
     *
     * @param panel The panel that we want to show.
     * @param panelTitle The title to set when showing the panel.
     */
    private void redirectTo(JPanel panel, String panelTitle) {
        this.setTitle(panelTitle);
        this.openPanel(panel);
    }

    /**
     * Redirect to the about panel.
     */
    private void redirectToAbout() {
        String aboutName = Localization.getLocalization(LocalizationKey.ABOUT);
        this.redirectTo(new AboutPanel(), aboutName);
        this.aboutButton.setText(aboutName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        aboutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        aboutButton.setText("${ABOUT}");
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutButtonMouseClicked(evt);
            }
        });
        menuBar.add(aboutButton);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseClicked
        this.redirectToAbout();
    }//GEN-LAST:event_aboutButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutButton;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
