package shared.presentation;

import customer.presentation.panels.RegisterCustomerPanel;
import java.awt.Container;
import javax.swing.JPanel;
import shared.application.configuration.ApplicationConfiguration;
import shared.application.configuration.ConfigurationVariable;
import shared.presentation.localization.Localization;
import shared.presentation.localization.LocalizationKey;
import shared.presentation.panels.AboutPanel;

/**
 * Main application frame.
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Constructor.
     */
    public MainFrame() {
        initComponents();

        this.initializeMenu();
        this.redirectToAbout();
    }

    /**
     * Initialize all the menu items by setting the localized text for them.
     */
    private void initializeMenu() {
        String aboutName = Localization.getLocalization(LocalizationKey.ABOUT);
        this.aboutButton.setText(aboutName);

        String registerName = Localization.getLocalization(LocalizationKey.REGISTER);
        this.registerCustomer.setText(registerName);

        String customerName = Localization.getLocalization(LocalizationKey.CUSTOMER);
        this.customer.setText(customerName);
    }

    /**
     * Set the main frame title.
     *
     * Keep in mind that the application name will be always added at the end of
     * the title separated by a hyphen.
     *
     * @param title The title to set.
     */
    @Override
    public void setTitle(String title) {
        String applicationName = ApplicationConfiguration.getConfigurationVariable(ConfigurationVariable.NAME);
        String frameTitle = String.format("%s - %s", title, applicationName);
        super.setTitle(frameTitle);
    }

    /**
     * Open the given panel.
     *
     * @param panel The panel to open.
     */
    private void openPanel(JPanel panel) {
        Container layoutContainer = this.getContentPane();
        layoutContainer.removeAll();
        layoutContainer.add(panel);
        layoutContainer.repaint();
        layoutContainer.revalidate();
    }

    /**
     * Redirect to the given panel.
     *
     * @param panel The panel that we want to show.
     * @param panelTitle The title to set when showing the panel.
     */
    private void redirectTo(JPanel panel, String panelTitle) {
        this.setTitle(panelTitle);
        this.openPanel(panel);
    }

    /**
     * Redirect to the about panel.
     */
    private void redirectToAbout() {
        String aboutName = Localization.getLocalization(LocalizationKey.ABOUT);
        this.redirectTo(new AboutPanel(), aboutName);
        this.aboutButton.setText(aboutName);
    }

    /**
     * Redirect to the register customer panel.
     */
    private void redirectToRegisterCustomer() {
        String registerName = Localization.getLocalization(LocalizationKey.REGISTER);
        String customerName = Localization.getLocalization(LocalizationKey.CUSTOMER);
        String panelTitle = String.format("%s %s", registerName, customerName);
        this.redirectTo(new RegisterCustomerPanel(), panelTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        customer = new javax.swing.JMenu();
        registerCustomer = new javax.swing.JMenuItem();
        aboutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        customer.setText("${CUSTOMER}");

        registerCustomer.setText("${REGISTER}");
        registerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCustomerActionPerformed(evt);
            }
        });
        customer.add(registerCustomer);

        menuBar.add(customer);

        aboutButton.setText("${ABOUT}");
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutButtonMouseClicked(evt);
            }
        });
        menuBar.add(aboutButton);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseClicked
        this.redirectToAbout();
    }//GEN-LAST:event_aboutButtonMouseClicked

    private void registerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCustomerActionPerformed
        this.redirectToRegisterCustomer();
    }//GEN-LAST:event_registerCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutButton;
    private javax.swing.JMenu customer;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registerCustomer;
    // End of variables declaration//GEN-END:variables
}
